language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - bin/phpcs --colors -p --standard=ruleset.xml --extensions=php --severity=1 .
  - bin/phpunit --coverage-clover build/logs/coverage.xml

after_script:
  - bin/coveralls -v
